### PR TITLE
check, if try to use ourself - fix #323

### LINKED ISSUE #323: Need to check, if we use tempesta itself as backend
in config:

server 127.0.0.1:80; 

and tempesta listens on 80 port.

$ curl http://127.0.0.1:80

empty answer

$ curl -X POST http://127.0.0.1:80

system crashes
```
[tdb] Start Tempesta DB
[tempesta] Initializing Tempesta FW kernel module...
[tempesta]   init: cfg_if
[tempesta]   init: classifier
[tempesta]   init: tls
[tempesta]   init: http
[tempesta]   init: http_sticky
[tempesta]   init: server
[tempesta]   init: client
[tempesta]   init: sock_srv
[tempesta]   init: sock_clnt
[tempesta]   tfw_sched_hash: init
[tempesta] Registering new scheduler: hash
[tempesta]   tfw_sched_http: init
[tempesta] Registering new scheduler: http
[tempesta]   tfw_sched_rr: init
[tempesta] Registering new scheduler: round-robin
[tempesta]   Frang module init
[tempesta] Registering new classifier: frang
[tempesta] got state via sysctl: start
[tempesta] starting all modules...
[tdb] Opened table /opt/tempesta/db/filter.tdb: size=16777216 rec_size=20 base=ffff88003d400000
[tdb] Opened table /opt/tempesta/db/cache.tdb: size=268435456 rec_size=0 base=ffff88002d400000
[tempesta] Open listen socket on: 0.0.0.0
[tempesta]   start listening on socket: sk=ffff88001dbff100
[tempesta] modules are started
[tempesta] got state via sysctl: stop
[tempesta] stopping all modules...
[tdb] Close table 'cache'
[tdb] Close table 'filter'
[tempesta]   tfw_sched_hash: exit
[tempesta] Un-registering scheduler: hash
[tempesta]   tfw_sched_http: exit
[tempesta] Un-registering scheduler: http
[tempesta]   tfw_sched_rr: exit
[tempesta] Un-registering scheduler: round-robin
[tempesta]   Frang module exit[tempesta] exiting...
[tdb] Shutdown Tempesta DB
[tdb] Start Tempesta DB
[tempesta] Initializing Tempesta FW kernel module...
[tempesta]   init: cfg_if
[tempesta]   init: classifier
[tempesta]   init: tls
[tempesta]   init: http
[tempesta]   init: http_sticky
[tempesta]   init: server
[tempesta]   init: client
[tempesta]   init: sock_srv
[tempesta]   init: sock_clnt
[tempesta]   tfw_sched_hash: init
[tempesta] Registering new scheduler: hash
[tempesta]   tfw_sched_http: init
[tempesta] Registering new scheduler: http
[tempesta]   tfw_sched_rr: init
[tempesta] Registering new scheduler: round-robin

[tempesta]   Frang module init[tempesta] Registering new classifier: frang
[tempesta] got state via sysctl: start
[tempesta] starting all modules...
[tempesta]   new server group: 'default'
[tdb] Opened table /opt/tempesta/db/filter.tdb: size=16777216 rec_size=20 base=ffff88003d400000
[tdb] Opened table /opt/tempesta/db/cache.tdb: size=268435456 rec_size=0 base=ffff88002d400000
[tempesta] Open listen socket on: 0.0.0.0
[tempesta]   start listening on socket: sk=ffff88001d215180
[tempesta]   tfw_sched_http: begin sched_http_rules
[tempesta]   tfw_sched_http: parsed rule: match  'default'=ffff88001bf18ec0  '*'=1  '*'=1  '*'
[tempesta]   tfw_sched_http: finish sched_http_rules
[tempesta] modules are started
[tempesta]   connected: 127.0.0.1
[tempesta]   connected: 127.0.0.1
[tempesta]   connected: 127.0.0.1
[tempesta]   connected: 127.0.0.1
[tempesta]   new client resource accounting: ::ffff:7f00:1
[tempesta]   new client: cli=ffff88001c129670
[tempesta]   new client: cli=ffff88001c129610
[tempesta]   new client: cli=ffff88001c1295b0
[tempesta]   new client: cli=ffff88001c129550
[tempesta]   new client: cli=ffff88001c1297f0
[tempesta]   Link new msg ffff88001d212020 with connection ffff88001c1d4768
[tempesta]   Add skb ffff88001beb5588 to message ffff88001d212020
[tempesta]   GFSM exec fsm 0, state 0x2000
[tempesta]   parse 73 client data bytes (GET / HTTP/1.1
User-Agent: curl/7.38.0
Host: localhost
Accept: */*

) on req=ffff88001d212020
[tempesta]   GFSM move from 0x2000 to 0x2
[tempesta]   GFSM switch from fsm 0 at state 2 to fsm 2 at state 0x400
[tempesta]   GFSM exec fsm 2, state 0x2400
[tempesta]   Matching request: ffff88001d212020, list: ffff88001d217020
[tempesta]   tfw_sched_http: use server group: 'default'
[tempesta]   Link new msg ffff88001d2a4020 with connection ffff88001c1d45b0
[tempesta]   Add skb ffff88001e355800 to message ffff88001d2a4020
[tempesta]   GFSM exec fsm 0, state 0x2000
[tempesta]   parse 71 client data bytes (GET / HTTP/1.1
User-Agent: curl/7.38.0
Host: localhost
Accept: */*
) on req=ffff88001d2a4020
[tempesta]   parse 52 client data bytes (X-Forwarded-For: 127.0.0.1
Connection: keep-alive
) on req=ffff88001d2a4020
[tempesta]   parse 2 client data bytes (
) on req=ffff88001d2a4020
[tempesta]   GFSM move from 0x2000 to 0x2
[tempesta]   GFSM switch from fsm 0 at state 2 to fsm 2 at state 0x400
[tempesta]   GFSM exec fsm 2, state 0x2400
[tempesta]   Matching request: ffff88001d2a4020, list: ffff88001d217020
[tempesta]   tfw_sched_http: use server group: 'default'
[tempesta]   Link new msg ffff88001d20e020 with connection ffff88001c1d4558
[tempesta]   Add skb ffff88001d1455c0 to message ffff88001d20e020
[tempesta]   GFSM exec fsm 0, state 0x2000
[tempesta]   parse 71 client data bytes (GET / HTTP/1.1
User-Agent: curl/7.38.0
Host: localhost
Accept: */*
) on req=ffff88001d20e020
[tempesta]   parse 26 client data bytes (X-Forwarded-For: 127.0.0.1) on req=ffff88001d20e020
[tempesta]   parse 11 client data bytes (, 127.0.0.1) on req=ffff88001d20e020
[tempesta]   parse 26 client data bytes (
Connection: keep-alive
) on req=ffff88001d20e020
[tempesta]   parse 2 client data bytes (
) on req=ffff88001d20e020
[tempesta]   GFSM move from 0x2000 to 0x2
[tempesta]   GFSM switch from fsm 0 at state 2 to fsm 2 at state 0x400
[tempesta]   GFSM exec fsm 2, state 0x2400
[tempesta]   Matching request: ffff88001d20e020, list: ffff88001d217020
[tempesta]   tfw_sched_http: use server group: 'default'
[tempesta] ERROR: can't add X-Forwarded-For header for 127.0.0.1 to msg ffff88001d20e020
[tempesta]   Send HTTP 500 response to the client
[tempesta]   Link new msg ffff88001d20e020 with connection ffff88001d22ca98
[tempesta]   Add skb ffff88001d1dd800 to message ffff88001d20e020
[tempesta]   GFSM exec fsm 0, state 0x2000
[tempesta]   parse 94 server data bytes (HTTP/1.1 500 Internal Server Error
Date: Wed, 21 Oct 2015 18:36:41 GMT
Content-Length: 0

) on resp=ffff88001d20e020
[tempesta]   GFSM move from 0x2000 to 0x4
[tempesta]   GFSM move from 0x2004 to 0x5
[tempesta]   Link new msg ffff88001d2a4020 with connection ffff88001d22c9e0
[tempesta]   Add skb ffff88001db8c980 to message ffff88001d2a4020
[tempesta]   GFSM exec fsm 0, state 0x2000
[tempesta]   parse 94 server data bytes (HTTP/1.1 500 Internal Server Error
Date: Wed, 21 Oct 2015 18:36:41 GMT
Content-Length: 0

) on resp=ffff88001d2a4020
[tempesta]   GFSM move from 0x2000 to 0x4
[tempesta]   GFSM move from 0x2004 to 0x5
[tempesta]   new client: cli=ffff88001c1297f0
[tempesta]   Link new msg ffff88001d212020 with connection ffff88001c1d4768
[tempesta]   Add skb ffff88001beb5c48 to message ffff88001d212020
[tempesta]   GFSM exec fsm 0, state 0x2000
[tempesta]   parse 73 client data bytes (GET / HTTP/1.1
User-Agent: curl/7.38.0
Host: localhost
Accept: */*

) on req=ffff88001d212020
[tempesta]   GFSM move from 0x2000 to 0x2
[tempesta]   GFSM switch from fsm 0 at state 2 to fsm 2 at state 0x400
[tempesta]   GFSM exec fsm 2, state 0x2400
[tempesta]   Cache: service request w/ key 21617b58
[tempesta]   new client: cli=ffff88001c129790
[tempesta]   Link new msg ffff88001c158020 with connection ffff88001c1d4710
[tempesta]   Add skb ffff88001beb5348 to message ffff88001c158020
[tempesta]   GFSM exec fsm 0, state 0x2000
[tempesta]   parse 74 client data bytes (POST / HTTP/1.1
User-Agent: curl/7.38.0
Host: localhost
Accept: */*

) on req=ffff88001c158020
[tempesta]   GFSM move from 0x2000 to 0x2
[tempesta]   GFSM switch from fsm 0 at state 2 to fsm 2 at state 0x400
[tempesta]   GFSM exec fsm 2, state 0x2400
[tempesta]   Cache: service request w/ key 21617b58
------------[ cut here ]------------
kernel BUG at /home/vlad/works/NatSys/Tempesta/tempesta/tempesta_fw/sock.c:166!
invalid opcode: 0000 [#1] SMP 
Modules linked in: tfw_frang(O) tfw_sched_rr(O) tfw_sched_http(O) tfw_sched_hash(O) tempesta_fw(O) tempesta_db(O) ipv6 fuse crc32c_intel ghash_clmulni_intel aesni_intel aes_x86_64 glue_helper lrw gf128mul ablk_helper cryptd i2c_piix4 i2c_core e1000 ppdev serio_raw microcode pcspkr parport_pc parport floppy [last unloaded: tempesta_db]
CPU: 0 PID: 1895 Comm: curl Tainted: G        W  O 3.10.10+ #6
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.7.5-20140531_083030-gandalf 04/01/2014
task: ffff88001d748000 ti: ffff88001c136000 task.ti: ffff88001c136000
RIP: 0010:[<ffffffffa01c760d>]  [<ffffffffa01c760d>] ss_send+0x4c/0x232 [tempesta_fw]
RSP: 0018:ffff88003fc03940  EFLAGS: 00010202
RAX: 0000000000000001 RBX: ffff88001c11f7c0 RCX: ffff88001d20e050
RDX: 0000000000000001 RSI: ffff88001d20e050 RDI: ffff88001d20e050
RBP: ffff88003fc03980 R08: ffffffff81ac8e88 R09: 0000000000000211
R10: ffff88002d41704c R11: 0000000000000210 R12: ffff88001beb5348
R13: 00000000000000b0 R14: ffff88001c11fdc8 R15: ffff88001c1d60b0
FS:  00007f060ee52740(0000) GS:ffff88003fc00000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 00007f060e9dc1c0 CR3: 000000001c15b000 CR4: 00000000000406f0
DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
Stack:
 ffffff01a01cecc0 ffff88001d20e050 ffff88001c11f7c0 ffff88003fc039f0
 ffff880000000040 ffff88003fc03900 ffff88003fc03900 ffff88003fc03990
 ffff88003fc039a8 ffffffffa01aafb2 ffff88013fc039c0 ffff88001d20e020
Call Trace:
 <IRQ> 
 [<ffffffffa01aafb2>] tfw_connection_send+0x39/0x3b [tempesta_fw]
 [<ffffffffa01adef0>] tfw_http_req_cache_cb+0x3f/0x14f [tempesta_fw]
 [<ffffffffa01a6f72>] __cache_req_process_node+0xc8/0xdd [tempesta_fw]
 [<ffffffffa01adeb1>] ? tfw_http_adjust_resp+0x18/0x18 [tempesta_fw]
 [<ffffffffa01a7122>] tfw_cache_req_process+0x140/0x147 [tempesta_fw]
 [<ffffffffa01adeb1>] ? tfw_http_adjust_resp+0x18/0x18 [tempesta_fw]
 [<ffffffffa01ae1d0>] tfw_http_req_process+0x1d0/0x211 [tempesta_fw]
 [<ffffffffa01ae529>] tfw_http_msg_process+0x46/0x60 [tempesta_fw]
 [<ffffffffa01ac4e8>] __gfsm_fsm_exec+0xff/0x171 [tempesta_fw]
 [<ffffffffa01ac599>] tfw_gfsm_dispatch+0x3f/0x41 [tempesta_fw]
 [<ffffffffa01ab104>] tfw_connection_recv+0x150/0x152 [tempesta_fw]
 [<ffffffffa01c817f>] ss_tcp_process_data+0x1fe/0x374 [tempesta_fw]
 [<ffffffffa01c843d>] ss_tcp_data_ready+0x71/0xb9 [tempesta_fw]
 [<ffffffff81469b57>] tcp_data_queue+0x457/0xcd0
 [<ffffffff8146cdd7>] tcp_rcv_established+0x1b7/0x890
 [<ffffffff81478414>] tcp_v4_do_rcv+0x1b4/0x500
 [<ffffffff81245407>] ? tempesta_sock_tcp_rcv+0x27/0x30
 [<ffffffff814796de>] tcp_v4_rcv+0x6fe/0x7f0
 [<ffffffff814529b4>] ip_local_deliver_finish+0xd4/0x210
 [<ffffffff81452cc8>] ip_local_deliver+0x88/0x90
 [<ffffffff81452633>] ip_rcv_finish+0x83/0x330
 [<ffffffff81452f40>] ip_rcv+0x270/0x340
 [<ffffffff8141a99a>] __netif_receive_skb_core+0x40a/0x8a0
 [<ffffffff810746fb>] ? try_to_wake_up+0x1eb/0x2e0
 [<ffffffff8141ae4b>] __netif_receive_skb+0x1b/0x70
 [<ffffffff8141b9e4>] process_backlog+0xa4/0x160
 [<ffffffff8141b209>] net_rx_action+0x129/0x210
 [<ffffffff81048489>] __do_softirq+0x119/0x260
 [<ffffffff814f29bc>] call_softirq+0x1c/0x30
 <EOI> 
 [<ffffffff8100437d>] do_softirq+0x3d/0x80
 [<ffffffff81047e09>] local_bh_enable+0x99/0xa0
 [<ffffffff8145715b>] ip_finish_output+0x1bb/0x3b0
 [<ffffffff81458b10>] ip_output+0x90/0xa0
 [<ffffffff81458255>] ip_local_out+0x25/0x30
 [<ffffffff814585ab>] ip_queue_xmit+0x14b/0x3d0
 [<ffffffff81470430>] tcp_transmit_skb+0x410/0x8e0
 [<ffffffff81470a87>] tcp_write_xmit+0x187/0xb40
 [<ffffffff8147164e>] __tcp_push_pending_frames+0x2e/0xd0
 [<ffffffff8145fe93>] tcp_push+0x53/0xc0
 [<ffffffff81464d2b>] tcp_sendmsg+0x79b/0xc40
 [<ffffffff8145715b>] ? ip_finish_output+0x1bb/0x3b0
 [<ffffffff8148bdc2>] inet_sendmsg+0x62/0xb0
 [<ffffffff81404449>] sock_sendmsg+0x99/0xd0
 [<ffffffff8112cb61>] ? handle_pte_fault+0x91/0x960
 [<ffffffff81404a21>] SYSC_sendto+0x121/0x1c0
 [<ffffffff814051ae>] SyS_sendto+0xe/0x10
 [<ffffffff814f1782>] system_call_fastpath+0x16/0x1b
Code: 48 83 7d d0 00 0f 94 c0 0f b6 c0 48 85 c0 74 02 0f 0b 48 8b 45 c8 48 89 c7 e8 e2 fb ff ff 85 c0 0f 95 c0 0f b6 c0 48 85 c0 74 02 <0f> 0b 48 8b 45 d0 48 83 c0 50 48 89 c7 e8 84 f2 ff ff 48 89 c7 
RIP  [<ffffffffa01c760d>] ss_send+0x4c/0x232 [tempesta_fw]
 RSP <ffff88003fc03940>
---[ end trace 2222dd08c7200260 ]---
Kernel panic - not syncing: Fatal exception in interrupt
```

### PR DESCRIPTION
**Pull request by vladtcvs**

### CODE REVIEW

File: tempesta_fw/sock_clnt.c [hunk 1]
```diff
@@ -348,6 +357,83 @@ tfw_listen_sock_stop_all(void)
 }
 
 /*
+ * Check, if client addr matches server addr
+ * server - backend address:port
+ * listener - listener address:port, address can be 0.0.0.0
+ */
+int
+tfw_sock_match_server_client(const TfwAddr *server, const TfwAddr *listener)
+{
```
Comment (krizhanovsky) [inline tempesta_fw/sock_clnt.c]: The function should be in addr.[ch]. Also there is tfw_addr_eq() and standard IN_LOOPBACK() which should be used to minimize code of the function.

File: tempesta_fw/server.c [hunk 2]
```diff
@@ -185,6 +186,27 @@ tfw_sg_del(TfwSrvGroup *sg, TfwServer *srv)
...
+		list_for_each_entry(srv, &sg->srv_list, list) {
+			if (tfw_sock_match_server_client(&srv->addr, addr))
+				return 1;
+		}
+	}
+	read_unlock(&sg_lock);
+
+	TFW_DBG2("Not found matching backends - ok\n");
+	return 0;
+}
```
Comment (krizhanovsky) [inline tempesta_fw/server.c]: It's better to update ```tfw_sg_for_each_srv()``` that it can return integer signaling about error.

File: tempesta_fw/sock_clnt.c [hunk 3]
```diff
@@ -348,6 +357,83 @@ tfw_listen_sock_stop_all(void)
...
+
+/*
+ * Checking, if addr is in the list.
+ */
+int
+tfw_sock_if_listen_addr(const TfwAddr *addr)
+{
+	TfwListenSock *ls;
+
+	TFW_DBG("Checking configuration: %s\n", __func__);
```
Comment (krizhanovsky) [inline tempesta_fw/sock_clnt.c]: Please make it TFW_DBG2

File: tempesta_fw/sock_clnt.c [hunk 4]
```diff
@@ -348,6 +357,83 @@ tfw_listen_sock_stop_all(void)
...
+
+	list_for_each_entry(ls, &tfw_listen_socks, list) {
+		TFW_DBG2("\tchecking...\n");
+		if (tfw_sock_match_server_client(addr, &ls->addr))
+			return 1;
+	}
+	TFW_DBG2("Not found matching listening sockets - ok\n");
```
Comment (krizhanovsky) [inline tempesta_fw/sock_clnt.c]: Please make it TFW_DBG3

File: tempesta_fw/sock_clnt.h [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+
+#include "cfg.h"
+#include "classifier.h"
+#include "client.h"
+#include "connection.h"
+#include "log.h"
+#include "sync_socket.h"
+#include "tempesta_fw.h"
+
+int tfw_sock_if_listen_addr(const TfwAddr *addr);
```
Comment (krizhanovsky) [inline tempesta_fw/sock_clnt.h]: It'd be better just to use client.h for the declaration.

File: tempesta_fw/sock_clnt.h [hunk 6]
```diff
@@ -0,0 +1,39 @@
...
+int tfw_sock_match_server_client(const TfwAddr *server,
+				 const TfwAddr *listener);
```
Comment (krizhanovsky) [inline tempesta_fw/sock_clnt.h]: Should be moved to addr.h

File: tempesta_fw/addr.c [hunk 7]
```diff
@@ -29,6 +29,69 @@
 #include "lib.h"
 #include "log.h"
 
+static bool
+tfw_addr_eq_inet(const struct sockaddr_in *a, const struct sockaddr_in *b);
+
+static bool
+tfw_addr_eq_inet6(const struct sockaddr_in6 *a, const struct sockaddr_in6 *b);
```
Comment (krizhanovsky) [inline tempesta_fw/addr.c]: Usually we don't use functions forward declarations, rather it's better to place ```tfw_addr_ifmatch()``` after ```tfw_addr_eq_inet()``` and ```tfw_addr_eq_inet6()```

File: tempesta_fw/addr.c [hunk 8]
```diff
@@ -29,6 +29,69 @@
...
+			unsigned laddr = listener->v4.sin_addr.s_addr;
+			unsigned saddr = server->v4.sin_addr.s_addr;
+			TFW_DBG3("listener: %i.%i.%i.%i:%i\n",
+				 (laddr) & 0xFF, (laddr >> 8) & 0xFF,
+				 (laddr >> 16) & 0xFF, (laddr >> 24) & 0xFF,
+				 htons(listener->v4.sin_port));
+			TFW_DBG3("server: %i.%i.%i.%i:%i\n",
+				 saddr & 0xFF, (saddr >> 8) & 0xFF,
+				 (saddr >> 16) & 0xFF, (saddr >> 24) & 0xFF,
+				 htons(server->v4.sin_port));
```
Comment (krizhanovsky) [inline tempesta_fw/addr.c]: I think the debug prints are redundant

File: tempesta_fw/server.c [hunk 9]
```diff
@@ -231,13 +233,18 @@ tfw_sg_for_each_srv(void (*cb)(TfwServer *srv))
 	list_for_each_entry(sg, &sg_list, list) {
 		write_lock(&sg->lock);
 
-		list_for_each_entry(srv, &sg->srv_list, list)
-			cb(srv);
-
+		list_for_each_entry(srv, &sg->srv_list, list) {
+			int ret;
+			TFW_DBG3("Iterating server...\n");
```
Comment (krizhanovsky) [inline tempesta_fw/server.c]: Also redundant debug print

**Comment by krizhanovsky** [comment]
Good to merge with the small cleanups
